apiVersion: batch/v1
kind: Job
metadata:
  name: exoplanet-extractor
  namespace: de
spec:
  template:
    spec:
      containers:
      - name: extractor
        image: 192.168.0.9:32000/haumea-science/star-exoplanet:latest
        args: ["extract"]
        env:
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: starexoplanet-credentials
              key: RABBITMQ_PASS
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: starexoplanet-credentials
              key: RABBITMQ_USER
      restartPolicy: Never
