apiVersion: batch/v1
kind: Job
metadata:
  name: astro-gaia-raw
  namespace: de
spec:
  template:
    spec:
      containers:
      - name: astroraw
        image: 192.168.0.9:32000/astro-gaia-raw:1.12.0
        imagePullPolicy: Always
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: accessKey
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: secretKey
      restartPolicy: Never
